{% set version = "2.9.2" %}
{% set name = "pari" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://pari.math.u-bordeaux.fr/pub/pari/unix/{{ name }}-{{ version }}.tar.gz
  sha256: 9aa24cbbcf4e0b09dcc21cf9b09f2eb08e38ee16ab13651be7274c9b3e46207e
  patches:
    # Jeroen Demeyer - Add -fno-common to DLCFLAGS on
    # Darwin. Submitted upstream, but upstream only applied it for PowerPC.
    # Since this doesn't break anything and only improves performance, add
    # the flag unconditionally
    - patches/get_dlcflags.patch
    # Jeroen Demeyer - Use PROT_NONE for unused virtual stack memory
    - patches/prot_none.patch
    # Jeroen Demeyer - https://trac.sagemath.org/ticket/19883
    # do not display warnings regarding the stack size (unless DEBUGMEM is set).
    - patches/stackwarn.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - gmp >=5.0.1,<7
    - readline 6.2*
    - perl 5.22.0.1
    - curl
    - openssl 1.0.*
  run:
    - gmp >=5.0.1,<7
    - readline 6.2*
    - perl

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/include/{{ name }}/anal.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://pari.math.u-bordeaux.fr
  license: GPLv2+
  license_file: {{ SRC_DIR }}/COPYING
  summary: PARI/GP is a widely used computer algebra system designed for fast computations in number theory
  dev_url: http://pari.math.u-bordeaux.fr/cgi-bin/gitweb.cgi
  doc_url: http://pari.math.u-bordeaux.fr/dochtml/html-stable/

extra:
  recipe-maintainers:
    - isuruf
