travis:
  secure:
    BINSTAR_TOKEN: HrlBvDNl5Xk6BhN+iuWOdN57lU1ek4v0qT43O0tnwE9Og+AOvHRT4bQIekDW2O9Yq6OGJkta0YeXW8/SMfcBK8F3Ni3Zitdn8FGQgVJ6tLiGpbfeI0e/mYllXLD12De1LzdzuPda1mlq3vKm0otFT4KtePEqIG3hRneQzuX5JaZU02DaTvWJHCl1keHnldOWhRODHXuiqJzBa+trjDW0cjdF7ddKCZHMYg0bIBXoEtmBxOsDKpoR16LGSWoXeb6RGhflvFap3vtU7B/vnDex6OvZMdvIvSvjXNzfSHHr1Zs0h9ZrUy+vxggaWUr8PiV1AzT0LNEFbG/Z7lkk701Ue91UXv/Gu8Ou/EhnRea88FpwikKQriagkJu6ESekDgfmpV8bGrDU9eAa2E3xukyghJ2OXWABEi598Aaz46XCfUdlUWwqT9zIb+Ows3XH3XUXDQP9GX28F5kbLnHbiIU0iQEBOkUEH3uUnVwAydwjGpiuwuraf/99ZYkPzjtH3ke5Wf5+mtwm1cwZKLCaY3SrvIcwI7ZXrkw7yH+p+7myjg/8ByOkoeUqLtDoFUlzuZVpNc2wm6smhWTYllP2j/kb/445OeDXez5zY3QUGSGdtj69ugScVzDyF/EhQ+212qiBlbSbL5LvObmdySysfWkp9G/+o8mmUDffv0pwm7ZLunc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
